name: "Python UV Setup"
description: "Set up Python + uv cache + sync"
runs:
  using: "composite"
  steps:
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: ${{ inputs.python-version }}
    - name: Install uv
      shell: bash
      run: python -m pip install --upgrade pip uv
    - name: Cache uv http cache
      uses: actions/cache@v4
      with:
        path: ~/.cache/uv
        key: ${{ runner.os }}-uv-${{ hashFiles('**/pyproject.toml') }}
        restore-keys: |
          ${{ runner.os }}-uv-
    - name: Sync dependencies
      shell: bash
      run: |
        extras="${{ inputs.extras }}"; devFlag=""; if [ "${{ inputs.dev }}" = "true" ]; then devFlag="--extra dev"; fi
        uv sync $devFlag $extras --python ${{ inputs.python-version }}
inputs:
  python-version:
    required: true
    default: "3.11"
  dev:
    required: false
    default: "true"
  extras:
    required: false
    default: ""
